### ISSUE TITLE
bug: opening saved project .cht file with chtracker.exe doesn't start software with project loaded, results in help file display error

### ISSUE THREAD

**Issue by mattlohkamp** [Chasyxx/chtracker#6]
it's pretty normal to take a saved file, and 'open with' it with the software that saved it - steps to reproduce (in windows):
- run chtracker.exe
- save project file (e.g. `c:\test\test.cht`)
- close chtracker
- double-click `test.cht` (or right-click and choose 'open with...')
- choose chtracker.exe as the program to open the saved project file with
- see that chtracker opens, but displays an error message, and doesn't load the specified project file:
![image](https://github.com/Chasyxx/chtracker/assets/139312/772c7b14-6bab-40ab-9871-0b3c10e9bdd9)
 - the same behavior happens when you click and drag the project .cht file onto the chtracker.exe executable

don't quote me on this but I am _guessing_ that 'open with...' or dragging the file onto the exeutable is equivalent to invoking the executable from the command line, using the project path as the first argument
(e.g. `> C:\chtracker\chtracker.exe "C:\test\text.cht"`)

(to be explicit, the expected behavior is that the tracker should launch, with the project file already loaded.)

**Comment by Chasyxx** [comment]
The help issue is a result of the program being started in a directory that doesn't have `./doc/help.txt`. If you run the program outside of where you extracted it, it has no idea where to possibly find the file on Windows, since there isn't a well known "static" spot it can check (whereas on Linux it can check the absolute path `/usr/share/doc/chtracker/help.txt`). That is just the result of how the program is opened rather than a bug in the program itself. That issue can be fixed just by writing the help to some location such as `%appdata%\chtracker\help.txt`, though i'm not sure how to get the appdata folder or make the chtracker folder if it doesn't exist.

As for a file not opening when you use open with or drag it onto the exe, the program doesn't care about command-line arguments yet. I can make it use the first argument as a path to a project and load it after init.

**Comment by mattlohkamp** [comment]
huh interesting. any chance of being able to use something like `SDL_GetBasePath` or `SDL_GetPrefPath`? It seems like there has to be a way to find the actual original location of the executable, even if it's currently being launched in the context of another directory.

**Comment by Chasyxx** [comment]
> It seems like there has to be a way to find the actual original location of the executable

If open with and similar give an absolute path to argv[0] then bingo.

**Comment by Chasyxx** [comment]
I figured out the methods to get the `doc` folder where the executable is (Windows and Linux!), see [this commit](https://github.com/Chasyxx/chtracker/commit/44514078ede2430fc1c412400c4729b84eca0386). Now the help should always load if `doc/help.txt` is in the same place as the exe. Best thing about this is this can be expanded and now preferences can be saved easily across program executions. I'll certainly use that in the future.

Now the first command-line argument `argv[1]` will be taken as a path to attempt to load if it exists (`argc` > 1) ([commit](https://github.com/Chasyxx/chtracker/commit/83212b809794a9b4150f5a98f6cebea785ecea13)). This resolves the file-dropping issue.
